package com.ikea.oms.order_service.event;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class OrderCreatedEvent {

    private Long orderId;
    private String orderNumber;      // business order number (generated by Order Service)
    private Long sagaOrderId;        // correlation id from orchestrator
    private String skuCode;
    private Integer quantity;
}

